apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/potopaa/HW_3_ArgoCD'
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-gitops-new
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
