apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gitops
  namespace: new-hello-gitops
spec:
  ingressClassName: nginx  
  rules:
    - host: http://a66a412735d2c4332abcd83d271c0ac2-1930463142.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-gitops
                port:
                  number: 8050
