apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/deployment-blue.yaml
- k8s/deployment-green.yaml
- k8s/service.yaml
- k8s/ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: potopaa/hello-gitops
