apiVersion: v1
kind: Service
metadata:
  name: hello-gitops
  namespace: new-hello-gitops
spec:
  type: LoadBalancer    
  selector:
    app: hello-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
